#!/usr/bin/env bash
# A script that transfer a file the client to the server

if [ $# -lt 3 ]; then
    echo 'usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

elif [ "$#" -lt 4]; then
	scp -o stricthostkeychecking=no "$1"  "$3@$2":~/
else
	scp -i "$4" -o StrictHostkeyChecking=no "$1" "$3@$2":~/
fi
