#!/usr/bin/env bash
# A script that transfer a file the client to the server

if [ $# -lt 3 ]; 
then
    echo 'usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o "stricthostkeychecking=no" -i "$4" "$1" "$32@$@#":~/
fi
